baseURL: "https://inwardmovement.github.io/"
title: "Inward Movement"
canonifyURLs: false
relativeURLs: false
disableFastRender: true
disableLiveReload: true
metaDataFormat: yaml
rssLimit: 10
enableRobotsTXT: true
enableEmoji: true
disableKinds:
- taxonomy
- term
params:
  description: "Developer, author, musician"
  author: "Victor Massé"
  email: "victor.dhamma@gmail.com"
  github: "inwardmovement"
  discord: "99026681846587392"
author:
  name: "Victor Massé"
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: false
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: blackfriday
    renderer:
      hardWraps: true
      unsafe: true
      xHTML: false
  tableOfContents:
    startLevel: 1
    endLevel: 5
menu:
  main:
    - Name: "Home"
      URL: "/"
      Identifier: "home"
      weight: 1
    - Name: "Poems"
      URL: "/poems/"
      Identifier: "poems"
      weight: 2
  footer:
    - Name: "Legal notices"
      URL: "/legal-notices/"
      Identifier: "legal-notices"
      weight: 1
  recueils:
    - Name: "Fleurs persistantes"
      URL: "/poems/fleurspersistantes/"
      Identifier: "fleurspersistantes"
      weight: 1
    - Name: "SuperEro"
      URL: "/poems/superero/"
      Identifier: "superero"
      weight: 2
    - Name: "Poudre à rêver"
      URL: "/poems/poudrearever/"
      Identifier: "poudrearever"
      weight: 3
    - Name: "Méditations"
      URL: "/poems/meditations/"
      Identifier: "meditations"
      weight: 4
    - Name: "Érosphère"
      URL: "/poems/erosphere/"
      Identifier: "erosphere"
      weight: 5
