name: deploy-main

on:
  push:
    branches:
      - main

env:
  PRODUCTION: true
  HUGO_VERSION: '0.76.5'
  NODE_VERSION: '12.14.0'
  GH_PAT: ${{ secrets.PERSONAL_TOKEN_GH_PAGES }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
      if: success()
    - name: Install dependencies
      run: |
        npm ci --no-optional
        npm i -g postcss postcss-cli autoprefixer gulp-cli
      if: success()
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: ${{ env.HUGO_VERSION }}
        extended: true
      if: success()
    - name: Build site
      run: npm run _build
      if: success()
    - name: Deploy site
      uses: crazy-max/ghaction-github-pages@v2.1.2
      with:
        target_branch: public
        build_dir: public
      if: success()
